### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by ldez** [raeperd/recvcheck#3]
v0.0.x are not semver compliant because a bug fix cannot happen before a minor release or an impossible initial version v0.0.0.

The first tag should always be at least v0.1.0.

> PATCH version when you make backward compatible bug fixes

https://semver.org/

> How should I deal with revisions in the 0.y.z initial development phase?
>
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase

**Comment by raeperd** [comment]
Thanks released v0.1.0 for that 
https://github.com/raeperd/recvcheck/releases/tag/v0.1.0
