### ISSUE TITLE
Whitelist marshaler methods

### ISSUE THREAD

**Issue by jkroepke** [raeperd/recvcheck#7]
Hi,

as I know,  implementing `encoding.TextUnmarshaler`, `json.Unmarshaler` and `json.Marshaler`, `encoding.TextMarshaler` on the same struct always result into mixed receiver type.

The code inside go tests following the same pattern

* https://github.com/golang/go/blob/583d750fa119d504686c737be6a898994b674b69/src/encoding/json/example_marshaling_test.go#L22-L51
* https://github.com/golang/go/blob/583d750fa119d504686c737be6a898994b674b69/src/encoding/json/example_text_marshaling_test.go#L22-L45

Which leads me into a situation where this is expected and should be not reported.

Ref: https://youtrack.jetbrains.com/issue/GO-13587

**Comment by raeperd** [comment]
Hi! Thank you for your detailed report!

While I acknowledge that mixing receiver types for interface implementations (like `encoding.TextUnmarshaler`, `json.Unmarshal`, etc.) is common in Go code, it can still lead to unexpected race condition errors with concurrent reads and writes. 

**Nevertheless, I agree that `recvcheck` can be improved by providing options to ignore specific types or functions.**

types from tests are ignored by default, but I believe providing the following options would make `recvcheck` more flexible from my findings below.

1. check private types // _default: false_
2. check Go primitives types (non-structs) // _default: false_ 
3. Ignore specific types // _default: []_
4. Ignore specific functions // _default: []_

@ldez 
would love to get your thoughts on this. Do you think I missed anything?

## findings
I examined the whole standard library and found 71 types that mix pointer and value receivers, with 27 being public types. Below is a breakdown of those public types:

Go Primitives: 4 types
Test-defined Types: 15 types
Other Public Types: 8 types

<details><summary>Details</summary>
<p>

### Go Primitives (4 types)
1. `json.RawMessage` ([]byte) << reported in this issue
2. `net.IP` ([]byte)
3. `slog.Level` (int)
4. `tar.Format` (int)

### Test-defined Types (15 types)
1. `debug.T` (int)
2. `gob.BinaryGobber` (int)
3. `gob.BinaryValueGobber` (string)
4. `gob.TextValueGobber` (string)
5. `gob.ValueGobber` (string)
6. `gob.Vector` ([]int)
7. `heap_test.IntHeap` ([]int)
8. `heap_test.PriorityQueue`
9. `json_test.Animal` (int) << reported in this issue
10. `json_test.Size` (int)
11. `reflect_test.Point`
12. `xml_test.Animal` (int)
13. `xml_test.Size` (int)
14. `xml.Animal`
15. `xml.Size` (int)

### Other Public Types (8 types)
1. `base32.Encoding`
2. `base64.Encoding`
3. `time.Time`
4. `token.Position`
5. `x509.OID`
6. `tar.Header`
7. `scanner.ErrorList`
8. `pkix.Name`

</p>
</details>

**Comment by ldez** [comment]
The mixing type receiver is a requirement for `encoding.TextUnmarshaler`, `json.Unmarshal`, etc.

**Comment by ldez** [comment]
I recommend not using the code of Go itself as a reference for coding style: the Go team doesn't have the same constraints as a "regular" application or a "regular" developer.
The code style of Go is something that should not be followed as a rule.

Just an example: there is globally no empty line inside the Go code, this makes the code hard to read. But it's their style, and they don't try to impose their style as a rule.

So I recommend using the Go team style with extreme caution.

**Comment by jkroepke** [comment]
> If possible, this should not be an option but the default.

As long as it is configurable through golang-ci, I'm happy.

**Comment by ldez** [comment]
> As long as it is configurable through golang-ci, I'm happy.

yes I agree, but as a golangci-lint maintainer, I prefer to have 0 false-positives by default :wink:.

**Comment by jkroepke** [comment]
Sound like `sql.Scanner` has the same issue as marshaler functions.

If there is an option like ignore specific interface implementations, that would be the best.

**Comment by raeperd** [comment]
@ldez @jkroepke 
Thanks for reply!

I tested some json.Marshaler & json.Unmarshaler implementations, mixing type is not causing problems if implementations does not updates struct's fields internally. 

For interfaces to handle by default following might be enough
- `encoding.BinaryMarshaler` / `encoding.BinaryUnmarshaler`
- `encoding.TextMarshaler` / `encoding.TextUnmarshaler`
- `json.Marshaler` / `json.Unmarshaler`
- `xml.Marshaler` / `xml.Unmarshaler`
- `gob.GobEncoder` / `gob.GobDecoder`
- `driver.Valuer` / `sql.Scanner`

**And fix for this issue could be type receiver use in Marshal/Encoding part of list is ignored by default.** 

Other options i mentioned earlier should be handled in separate issue.

**Comment by jkroepke** [comment]
Consider add YAML as well.

https://pkg.go.dev/gopkg.in/yaml.v3#Unmarshaler

While its not part of stdlib, its a good use-case if the implementation works with 3rd party as well.
