### ISSUE TITLE
Whitelist driver.Valuer interface

### ISSUE THREAD

**Issue by jlengelsen** [raeperd/recvcheck#9]
This issue is related to issue https://github.com/raeperd/recvcheck/issues/7 which has been fixed by PR https://github.com/raeperd/recvcheck/pull/8 in order to reduce the number of false positives in the default configuration of the linter.

The interfaces [driver.Valuer](https://pkg.go.dev/database/sql/driver#Valuer) and [sql.Scanner](https://pkg.go.dev/database/sql#Scanner) from the standard library conflict with each other and are commonly implemented by the same struct. This was already mentioned in this comment https://github.com/raeperd/recvcheck/issues/7#issuecomment-2468474729 but somehow was not implemented in the PR.

It would be nice to add driver.Valuer to the default exclusions.

**Comment by ldez** [comment]
Hello,

As I said in PR #8, the signatures of the SQL elements seem too "generic", it can lead to false negatives (some methods will be ignored, but they should not).

https://github.com/raeperd/recvcheck/pull/8#issuecomment-2480381982

**Comment by jlengelsen** [comment]
> Hello,
> 
> As I said in PR [#8 (comment)](https://github.com/raeperd/recvcheck/pull/8#issuecomment-2480381982), the signatures of the SQL elements seem too "generic", it can lead to false negatives (some methods will be ignored, but they should not).

Sounds like a valid point. I totally missed that comment. On the other hand the interface is part of the standard library and one could argue that its counterintuitive to use a pointer receiver on a method with the signature Value() (any, error). Though I understand its in conflict with the purpose of the linter itself.
